#!/usr/bin/env bash

mount_point=/media/usb
mount_device=/dev/sdc1
backup_path=~/main_archive.tar.gz
usb_backup_path=/media/usb/main_archive.tar.gz
dir_to_backup=~/main
dir_to_backup_size=$(du -sb $dir_to_backup | awk '{print $1}')

# Make sure to have sudo priviliges
sudo echo ""

echo "Archive & compress ~/main"
echo "===================="
echo ""

tar cf - $dir_to_backup | pv -s $dir_to_backup_size | gzip > $backup_path

echo "Copy archive to USB drive"
echo "===================="
echo ""

sudo mount $mount_device $mount_point
sudo rm -rf $usb_backup_path && sudo rsync --progress $backup_path $usb_backup_path
sudo umount $mount_point
